### ISSUE TITLE
Establish bond interest policy

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#30]
bisq-network/proposals#120 dealt with establishing an interest rate on bonds put up by bonded contributors. The discussion there is lengthy with many good arguments made, but in the end the proposal was intentionally closed without a clear decision.

In the meantime at least one contributor, @burningman2, has been requesting a 1% monthly interest rate on his 50000 BSQ bond, and this request was approved in his Cycle 9 compensation request (bisq-network/compensation#451).

I have requested that @burningman2 defer his interest payment from Cycle 10 to Cycle 11, pending a decision that we should make as to whether these requests will be honored in the future, and at what percentage rate. This way we can establish a consistent policy applicable to all bonded roles.

Now is a good time to re-assess this issue and make this decision, because we are currently in the process of an overall roles cleanup effort (#3). I have added this issue to the task list in (#3), and will make a point to arrive at a decision here prior to the deadline for Cycle 11 compensation request submission.

This is something I'd like discuss on the next team leads call (#29).

**Comment by wiz** [comment]
While I recognize that locking up capital into bonds is forbearing potential market-making trading opportunities or other uses of the capital, I think the more important issue that should probably be resolved before discussing this proposal (or perhaps somehow together with it), is that not all people who are performing bonded roles have posted their bonds yet, and so the financial incentives are not currently aligned properly to discuss this right now. Obviously the people who have already posted bonds will favor a higher rate, and the people who haven't posted their bonds yet will be against this proposal.

Perhaps we should merge this policy decision into the roles cleanup issue, so that together with enforcing the requirement for trusted role operators to post bond, they are also financially incentivized to do so.

**Comment by cbeams** [comment]
Agreed all around.

> Perhaps we should merge this policy decision into the roles cleanup issue

Already done. You'll notice on the right of this issue that it is part of the `Clean up roles` project. It is also linked from the description of the issue that tracks that project at #3.

**Comment by wiz** [comment]
If you take a look at our spreadsheet (still WIP), the total amount of all required bonds is something crazy like 770K BSQ. We should discuss which of these bonds we want to actually enforce or waive, and if we also want to lower the bond factor, and of course what the actual interest rate would be.

If we get the number down to 500K BSQ bonded, that means 1% per month would be 5000 BSQ issued each month just for bond interest which sounds quite high, but if you think of it as a form of dividends of Bisq revenue to BSQ stakeholders, or some kind of salary for being a bonded long-term contributor, it might make sense? Lots of external financial factors to consider as well, like what happens when the burning man buys all the available BSQ for sale and there's none left? Maybe issuing the bond interest is necessary to provide a type of liquidity to the market, since presumably people would sell that for BTC, and becomes a decentralized way of redistributing BTC revenue to Bisq to the stakeholders?

**Comment by cbeams** [comment]
Thanks for the numbers, @wiz. I think we should go with 0.25% bond interest per month. That gets bonded role owners (0.0025x12) 3% annual interest, and with the full 770K BSQ worth of bonds currently required, that would be just (770000x0.03) 23,100 BSQ worth of bond interest issued per year. The mechanism for collecting this interest would be requesting it in each compensation request, i.e. nothing fancy, no changes to the DAO, etc. I think this arrangement strikes the right balance of compensating bonded roles owners for the downside of holding their BSQ in an illiquid state, while adding only modest issuance and keeping the implementation simple.

If there are no objections, I'll create a proposal for this. If there is rough consensus in the GitHub issue, we'll enact this for Cycle 11 compensation requests. If it's contentious, we'll (potentially) put it to a vote in Cycle 11 for enactment in Cycle 12.

**Comment by wiz** [comment]
[As I said in the original bond interest proposal](https://github.com/bisq-network/proposals/issues/120#issuecomment-531057464), the term "bond interest" should be avoided, and instead we should simply re-define the monthly bonded role compensation for each role. Even if you do zero work for the bonded role, such as Domain Name Owner, it's valuable to the DAO, and justifies compensation for that role especially because of the capital locked up in the bond.

So as part of our role cleanup, IMO we should just assign a monthly compensation for each bonded role, which can be based on a percentage of the bond amount. This would also need to be reflected in the DAO budget, so for example 0.5% of a 20K BSQ bond for "seednode operator" is 100 BSQ, so we could simply increase the compensation for that role to 200 BSQ. All teams would have to make similar budget adjustments. Then we avoid any controversy drama, enforce the bond requirement, and fit the "bond interest" into our budget all at the same time.

**Comment by cbeams** [comment]
Closing as dropped along with aborting its parent project. We never got to a consensus here, and this issue has languished now for a few months. If someone wishes to pick it back up, that's great, but clearing it from the decks for now.
