### ISSUE TITLE
Update compensation request maintainer role duties to include adding a calendar event for issue submission deadline

### ISSUE THREAD

**Issue by cbeams** [bisq-network/admin#56]
- [x] @cbeams to grant @mwithm rights to edit the bisq events calendar
- [ ] @mwithm to add calendar event for cycle 11 compensation request issue submission deadline
- [ ] @mwithm to update https://bisq.wiki/Compensation_Maintainer documentation to include this new duty
- [ ] @cbeams to review

/cc bisq-network/roles#86

**Comment by cbeams** [comment]
@MwithM, you have edit access to the calendar now, and I've also just added https://bisq.wiki/Events_Calendar.

**Comment by MwithM** [comment]
I tried to simplify the calendar using concrete days instead of periods. All DAO phase beginnings are announced -the start of phases are close to the end of the last phase of a cycle-, and the most critical deadline (DAO submission) is detailed by the block and estimated hour to be mined and also by the day it should happen as well.
At the wiki, I just stated that the announce for submission deadline will be also made at the Bisq Events calendar, together with DAO discussions and Compensation Board. Maybe this needs to be more specific.

**Comment by cbeams** [comment]
Did you see the dao discussion this morning as to why I deleted the phases from the calendar? They are always wrong by default due to the block time mismatch and I don’t think they’re adding value to anyone. I think it’s just noise to have them there (as periods or specific times). The only thing that really matters is that folks get a reminder about the issue submission deadline. Could we leave it to just that on the calendar? It’s less work for you that way as well.

**Comment by MwithM** [comment]
To me, the noise came because periods were announced instead of specific times. You don't need to be reminded every day you're in the proposal phase, but it might be good to remind reveal phase. I thought that if I edit the times as the blocks are getting nearer, mismatch won't be very high.
Anyway, it's less work and nobody asked for it, so I've performed the changes. Now only the day for _CR ready for review_ is indicated on the calendar.

**Comment by cbeams** [comment]
Thanks, @MwithM. Note that I changed the text of the invitation and the link in the notes. Using an abbreviation like "CR" (as the calendar event previously read) is cryptic for newcomers. Even I didn't know what people were talking about the other day when I saw CR mentioned in a chat conversation. This change spells it out and makes it clear that there is a deadline for submitting compensation request _issues_. It's verbose, but clear.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/301810/75439690-903bfa80-595a-11ea-99cb-8fc666198ac6.png">
